### ISSUE TITLE
system update

### ISSUE THREAD

**Issue by SnowCrestGuy** [helloSystem/Utilities#107]
A number of "no such file or  directory" notices 
About this Computer reports 0G142
Time for reboot

**Comment by SnowCrestGuy** [comment]
On reboot 'About this Computer' reports 0G142 not 0G145

**Comment by probonopd** [comment]
The Update.app will update FreeBSD and FreeBSD packages, so that you get the latest security patches for those. E.g., from 13.0-RELEASE to 13.0-RELEASE-p4. It does not update the helloSystem build. A 0G142 build will currently always stay 0G142 until you install a newer one.
