### ISSUE TITLE
Users: Make it possible to disable automatic login

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#108]
https://jwestall.com/blogs/hello-system-review.html

> However, there are a few caveats to using helloSystem. The first and most prominent is that there isn't really a login screen. When you first boot the computer it will boot strait to a desktop. This might be okay and how they did it back in the classic Macintosh days, but we live in a day and age where computer security is something that needs to be taken seriously. Having that password barrier is something that is necessary, especially with laptops.

helloSystem does have a session manager ("login window"), `slim`, but we set it io log in the default user automatically.

Indeed the Mac did without this feature for the first decade or so, but we should have a GUI item to disable automatic login, or to change which user is logged in automatically..

**Comment by probonopd** [comment]
In the meantime:

In `/usr/local/etc/slim.conf`, change to `no` or comment out

```
auto_login          yes
```

**Comment by louies0623** [comment]
"Neither do people pour new wine into old wineskins. If they do, the skins will burst; the wine will run out and the wineskins will be ruined."
Even if that guide is great, it won't wait.

**Comment by probonopd** [comment]
For now, auto-login can be disabled in `/usr/local/etc/slim.conf`; should we switch to a Qt native login manager we may consider to re-open this.
