### ISSUE TITLE
Unable to use Debian Runtime

### ISSUE THREAD

**Issue by 69graves** [helloSystem/Utilities#117]
helloSystem 0.7.0 (Build 0G160)
Developer Tools installed

`An error occurred: [Errno 2] No such file or directory: '/compat/debian.img'
`
When run from terminal, or Under Construction folder.

Here's the output from the terminal:

`debian does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
debian does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
Could not find suitable .ts files in /Applications/Under Construction/Install Debian Runtime.app/Resources/i18n
Preparing wizard
Preparing IntroPage
Preparing InstallationPage
Preparing SuccessPage
Displaying IntroPage
Getting releases from https://api.github.com/repos/helloSystem/LinuxRuntime/releases
onSelectionChanged
browser_download_url attribute:https://github.com/helloSystem/LinuxRuntime/releases/download/bullseye/debian.img
Displaying InstallationPage
Download started
https://github.com/helloSystem/LinuxRuntime/releases/download/bullseye/debian.img
socket.getdefaulttimeout(): 240.0
An error occurred: [Errno 2] No such file or directory: '/compat/debian.img'
Show error page
Preparing ErrorPage
Displaying ErrorPage
Playing sound
No sound available
Trying to copy rc script to /usr/local/etc/rc.d/debian
/bin/cp ['debian', '/usr/local/etc/rc.d/debian']
Trying to enable the service 'debian'
service ['debian', 'enable']
Trying to restart the service 'debian'
service ['debian', 'restart']
`

**Comment by probonopd** [comment]
This should be fixed by https://github.com/helloSystem/Utilities/commit/9c14c7aeece260e3f5bd352f2128e74553796116 in the most recent experimental ISO. Please comment here if it isn't. Thanks for reporting!
