### ISSUE TITLE
Cosmetic issue in FreeBSD Installer setting Computer Name with FQDN

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/Utilities#119]
**Steps to reproduce**:

1. Run the **FreeBSD Installer** and click **Continue** until you reach the **Create Local Computer Account** page.

2. Fill out the details including the fully qualified domain name in the **Computer Name** field.

3. Tick the box next to **Enable users to log in over the network (ssh)**.

**Actual behaviour**:

Under **Enable users to log in over the network (ssh)** it displays the FQDN with _.local_ appended to it. e.g. _daemon.mydomain.ro.local._

**Expected behaviour**:

_.local._ is only appended if the hostname provided by the user does not include the rest of the FQDN (e.g. _daemon.local._)

![fqdn](https://user-images.githubusercontent.com/6193091/149992959-5aea5e35-6a6c-473b-947c-5960e1caf09a.png)

**Comment by SanPollo** [comment]
> True, didn't think of this. So we should not append `.local.` in case the hostname contains `.`.
> Does this sound about right?

This was what I was thinking. If I actually test this on the command line, though, _hostname -s_ says _daemon_ and _hostname -f_ says _daemon.bromania.eu_ so it's only a cosmetic issue in the installer.

> For the Live system:
> https://github.com/helloSystem/ISO/blob/98b56318ce878a80b640db4478ef6fff6a2eb127/overlays/boot/boot/init_script#L191

On the live system this works well - I was impressed to see that my hostname was set to _E402M_. It is also correctly set in the installed version, and you can see this in at the Terminal prompt, and when using the _hostname_ command.

I was just surprised to see that in the installed version, _hostname_ is set to _"FreeBSD"_ in _/etc/rc.conf_. I guess it is setting it in the same way as it would with the live system, but with a user-specific hostname. It works absolutely fine, I was just wondering if it would be better to set it in _/etc/rc.conf_ to keep helloSystem closer to a standard FreeBSD installation?

I can also open a new issue for this if you like seeing as it is different to the issue I originally reported?

**Comment by probonopd** [comment]
Yes, please always open separate issues for everything that you think should be changed, so that ideally every issue can be closed by one commit (one change in a source code file). This helps a lot. Thanks!
