### ISSUE TITLE
Add a small game in hello

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#130]
A small game made in python is added to hello to make people have leisure time.
e.g.
- [Moonsweeper](https://github.com/learnpyqt/15-minute-apps/tree/master/minesweeper)   Mine stepping game.
- [Ronery-PyQt ](https://github.com/learnpyqt/15-minute-apps/tree/master/solitaire)    Card games, just the suit and tablecloth of the cards should be carefully selected.
- [QChess](https://github.com/Jaime02/QChess)     Chess game, Need a good chess picture or background (if possible)
- [python sudoku](https://www.askpython.com/python/examples/sudoku-solver-in-python)

**Comment by probonopd** [comment]
Maybe we can find something that is making more use of 3D/GPU, something kids love to play around with?

**Comment by louies0623** [comment]
Let's start with 2d mini-games, because this can test the stability of the system, such as the AI of single-player games, and also make sure that the game can be played on a computer with poor performance.
However, the maintenance and content presentation of 3D games are too challenging. I think this is not suitable for developers who are currently few in number.

**Comment by probonopd** [comment]
You may be right :)

**Comment by louies0623** [comment]
If possible I would like to add [Ping-Pong](https://github.com/AProjectAMonth/Ping-Pong) and [Breakoutu](https://github.com/angelortizv/Breakout) to commemorate the first video game and steve jobs

**Comment by probonopd** [comment]
helloSystem is meant as a minimalistic system for productive workstations. Games need to be downloaded separately.

**Comment by louies0623** [comment]
![image](https://user-images.githubusercontent.com/44593430/209960334-16e15ee5-69be-4e41-8fec-dc6fd2498022.png)
I miss the simple games in windows 7 without internet.
