### ISSUE TITLE
Install FreeBSD: Allow to install into partitions without wiping whole disk (multiboot)

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#137]
According to @pmhausen, EFI makes it really easy to install multiple operating systems these days without bootloaders overwriting each other, since EFI firmware itself seems to contain a bootloader of sorts. If it is really that easy, then __we "just" need a way to use something else in place of `bsdinstall zfsboot`__ which wipes the whole disk?

https://twitter.com/Sweordbora/status/1584239800718352384

But for the UEFI firmware to be able to read efi/freebsd/loader.efi, I suppose that needs to be written to the EFI System Partition (ESP), correct? How do you prevent multiple efi/freebsd/loader.efi from overwriting each other there?

> Each EFI compatible OS can place its boot loader in efi/<something>/ and the EFI BIOS will identify all "things" that are a correct boot loader binary and offer them for booting via some mechanism. If it's an older BIOS it will default to boot/bootx64.efi instead which was originally intended for removable media only.
> 
> If you install multiple boot loaders in e.g. freebsd/loader.efi and foobsd/loader.efi the BIOS will offer both. Everything after that is the boot loader's business. So to boot more than one.
> The firmware does not write that. The OS installer does. The firmware lets you pick from
>
><EFI partition>/efi/freebsd/loader.efi
<EFI partition>/efi/ubuntu/loader.efi
<EFI partition>/efi/windows/loader.efi
>...
>
> EFI is great! One FAT partition and no conflicting boot mechanisms.

**Comment by probonopd** [comment]
Any hints (especially: shell script examples) for how to multiboot install FreeBSD are welcome. Maybe we can work that into the installer if it can be made straightforward enough (no questions asked) and risk-free (no stealing bootability away from preexisting OSes) for the end user.

**Comment by CocoCR300** [comment]
What would be the preferred boot manager: GRUB, rEFInd, Clover, other?

**Comment by probonopd** [comment]
FreeBSD bootloader.

Fallback if absolutely needed: Clover or rEFInd.

**Comment by probonopd** [comment]
Closing as a duplicate of https://github.com/helloSystem/ISO/issues/140.

**Comment by karthik-holla** [comment]
Any solutions for those who want to multiboot hello system with Linux and windows?

**Comment by probonopd** [comment]
No, need use a separate SSD. No one has implemented this so far.

**Comment by pmhausen** [comment]
Install on a different system e.g. in a VM, boot a rescue system, use ZFS send/receive to transfer the pool.
rEFInd is a great EFI boot manager to use afterwards.

http://www.rodsbooks.com/refind/

**Comment by karthik-holla** [comment]
When freebsd can be dual booted as shown here 
[](https://forums.freebsd.org/threads/dual-boot-freebsd-and-linux-mint.81640/) why it is not possible for hello system?

**Comment by pmhausen** [comment]
It can be dual booted. Until now simply nobody had got the time to teach the installer how to perform a dual boot installation. Contributions welcome ;)

If you install on a second system, then manually partition the disk and restore the ZFS pool from a live/rescuee system, dual boot works.

**Comment by probonopd** [comment]
> Until now simply nobody had got the time to teach the installer how to perform a dual boot installation. Contributions welcome ;)

_Ideally_ `zfsboot` could learn how to (optionally) just use the unallocated space on an existing hard disk rather than all of the hard disk.
