### ISSUE TITLE
Feather-bad close notification

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#143]
![VirtualBox_PC-2_28_12_2022_22_19_42](https://user-images.githubusercontent.com/44593430/209826705-59b49e82-02ff-4f37-94b1-039d42d0d145.png)
No indication of which file to close.
Window text is not centered either.

**Comment by probonopd** [comment]
Thanks for reporting, however this would need to be addressed to https://github.com/tsujan/FeatherPad/issues.
Thanks!
