### ISSUE TITLE
Language.app: Persist selected language by writing EFI NVRAM

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#144]
Although there is a login language option, it is very annoying to have to select it every time you log in. However, you cannot directly enter the keyboard to select it when you log in, which is even more annoying; the system requires language settings.

**Comment by probonopd** [comment]
Language.app should persist the selected language by writing it to the `prev-lang:kbd` EFI variable.

**Comment by louies0623** [comment]
I think it is better to have a setting, in case someone accidentally clicks wrong (think about the language list, there is no color block selection box, it is easy to click wrong)

**Comment by louies0623** [comment]
Forgive my nonsense @probonopd , that is, if Apple can automatically detect the efi auto-detection language of Mac devices, they would have removed the language option on the first boot.

**Comment by louies0623** [comment]
Some PCs Don't Have EFI NVRAM So What Do You Do With It?

**Comment by probonopd** [comment]
Actually we are already doing this in Keyboard.app.
So it can be ported from there.

https://github.com/helloSystem/Utilities/commit/654fb0e3af5883fc5711552e9b5111ea34b4079c

**Comment by probonopd** [comment]
We are now also writing a `/usr/local/var/localize/include` file: 
 https://github.com/helloSystem/Utilities/commit/14351d5683652abb36046139efb16c04a4a49441
