### ISSUE TITLE
Battery: Display percentage as text next to the icon

### ISSUE THREAD

**Issue by CocoCR300** [helloSystem/Utilities#149]

**Comment by louies0623** [comment]
I agree, there should be an option to show percentages too.
like this
![image](https://github.com/helloSystem/Utilities/assets/44593430/c838d8f7-8955-4fbe-9e0e-f2b8ea6130c5)

**Comment by louies0623** [comment]
Indeed it got the message, Maybe the digital dosage is more clear to him.
