### ISSUE TITLE
Processes.app improvement

### ISSUE THREAD

**Issue by Hierosme** [helloSystem/Utilities#160]
After long test of Processes.app here my todolist

* Migrate totaly to psutils and use **oneshot** and **process_inter** speed up capability
* fit with the OsX Processes Monitor layout
* Create a tabs for CPU/System Memory/Disk/Network
* Have charts graph for CPU 
* Have chart pie for the Memory system
* Create a ToolBar for buttons
* Move the Force button ton the toolbar as original OsX Processes Monitor
* Create a dialog for process inspection, callable by  a Button name **Inspection** on the ToolBar
* Create ListBox with common filter, for a OneClick filter operation
* Create a Input Text for filter on the right of the ToolBar
* Create a dialog for Quit process with 3 buttons: Force Quit -> SIGKILL, Cancel -> Close the dialog, Quit -> SIGTERM
* Optimize the signal queue event system them limit the QT.Timer usage.
* Rename the App **Processes Monitor**
* Link **Processes Monitor** with the Menu.app
* Inform KWin to bind CTRL + ALT + SUPP to a Simplified view Dialog for Kill / Kill -HUP a Process (Like OsX)

Actually i working on:
- [  ] Migrate totaly to psutils and use **oneshot** and **process_inter** speed up capability
- [  ] fit with the OsX Processes Monitor layout
- [  ] Create a tabs for CPU/System Memory/Disk/Network
- [  ] Have charts graph for CPU 
- [  ] Have chart pie for the Memory system
- [  ] Create a ToolBar for buttons
- [  ] Move the Force button ton the toolbar as original OsX Processes Monitor
- [  ] Create a dialog for process inspection, callable by  a Button name **Inspection** on the ToolBar
- [  ] Create ListBox with common filter, for a OneClick filter operation
- [  ] Create a Input Text for filter on the right of the ToolBar
- [  ] Create a dialog for Quit process with 3 buttons: Force Quit -> SIGKILL, Cancel -> Close the dialog, Quit -> SIGTERM

PS: Yes i come from nowhere...

**Comment by Hierosme** [comment]
Here fews images link for better view about what i speack about

https://i.stack.imgur.com/zxYLq.png

https://etherealmind.com/wp-content/uploads/2011/02/restart-osx-processes-activity-monitor-4.jpg

https://etherealmind.com/wp-content/uploads/2011/02/restart-osx-processes-activity-monitor-2.jpg

**Comment by probonopd** [comment]
Let's make it welcoming to switchers from the Mac yet different enough so that it can't be mistaken for a copy.

**Comment by Hierosme** [comment]
Done with #159

**Comment by probonopd** [comment]
Hello @Hierosme. I did a quick test and it is very impressive. Very powerful. Will do some more testing.
Please feel free to add your name to the About dialog.
Thanks!

**Comment by Hierosme** [comment]
i just have add my name on the author credit:
![image](https://github.com/helloSystem/Utilities/assets/56162977/2da70bb4-e233-4c03-81a6-664090d16111)

**Comment by probonopd** [comment]
Thanks, also added you to https://hellosystem.github.io/docs/developer/acknowledgements.

**Comment by louies0623** [comment]
@Hierosme Please fix the ordering because it's way wrong, And shorten the "ForceQuite" button, I think you can also add the "End application with the mouse" in the System topmenu ![20230902_142102](https://github.com/helloSystem/Utilities/assets/44593430/2f3666c5-c050-484a-bd97-43730db189f2)

**Comment by probonopd** [comment]
Hierosme has completely rewritten this.
