### ISSUE TITLE
Cannot Set Date and Time

### ISSUE THREAD

**Issue by bert003** [helloSystem/Utilities#162]
This is my first time using helloSystem. Please bare with me. I found the following issues:

1. When trying to set the date, I get a message that Date and Time is not installed.

2. When I install Chrome, it says it is installed but does not appear in the menu. Also the disk named chrome remains mounted and I cannot eject it.

How do you install additional software please?

**Comment by bert003** [comment]
I have created a pull request where I have implemented the spinner on both tabs. Have a look at it and see if it is what you had in mind.

**Comment by probonopd** [comment]
Looks good, but we need to make room for the spinner.

**Comment by bert003** [comment]
What do you mean by "make room for the spinner" please?

**Comment by probonopd** [comment]
Uh, that is strange. The spinner should not overlay existing controls. 

We need to add some free space below the "Date and Time options" box, and have the spinner appear there.

**Comment by bert003** [comment]
Ok noted. Would you mind having the space underneath the "Set Date and Time Automatically" button appear only on button click? Or would you prefer a permanent space like the below?

![image](https://user-images.githubusercontent.com/20399702/235343810-f6d75126-b593-4d84-b66d-d9e837506701.png)

**Comment by bert003** [comment]
Also I feel that this should have a fixed size. What do you think?

When you resize, you end up with a lot of empty space.

**Comment by probonopd** [comment]
Thank you very much. By the way, you should really test your version on helloSystem, as this is where the utilities will run...

**Comment by bert003** [comment]
Welcome. Glad to be able to contribute. Did you have something in mind as regards the below?

# TODO: Implement manual date and time setting in the date and time tab

**Comment by probonopd** [comment]
I think this is a leftover, since one can now set the date and time manually.

**Comment by bert003** [comment]
Ok noted. So what did you have in mind re: the below then please?

# TODO: Implement manual time zone setting in the time zone tab

**Comment by probonopd** [comment]
A drop down where I can select "Europe/Berlin" etc.

**Comment by bert003** [comment]
Started implementing it. Requires pytz library.

![image](https://user-images.githubusercontent.com/20399702/235579327-7997d08e-ba87-4a50-8a74-f794179be0c9.png)

**Comment by bert003** [comment]
Auto Time Zone fully implemented and pushed to branch. Kindly check and revert at your convenience @probonopd

**Comment by bert003** [comment]
Any feedback please? Should this be considered as implemented?

**Comment by probonopd** [comment]
Thanks @bert003, let's continue the discussion in the PR at https://github.com/helloSystem/Utilities/pull/163.
