### ISSUE TITLE
Make the time zone user-selectable

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#168]
Realize the user's own location setting, so that the setting location can be customized, which is also user privacy.
![image](https://github.com/helloSystem/Utilities/assets/44593430/b7d0e9a4-345b-4f6a-9162-86ecd0ef90ab)

**Comment by probonopd** [comment]
Will be addessed by https://github.com/helloSystem/Utilities/pull/163 (although initially not with a nice fancy graphic yet).
