### ISSUE TITLE
This window was closed when the software was installed for the first time

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#174]
[PC-2-screen0.webm](https://github.com/helloSystem/Utilities/assets/44593430/b7cdfbd4-9eb3-4675-a17b-e8390716a164)

**Comment by probonopd** [comment]
This message is coming from `sudo`.

* Live ISO or installed system?
* What did you enter as the password?
* Does `sudo` work on the command line? Does it ask you for a password there?

**Comment by louies0623** [comment]
installed system.
It appears after you log in automatically and choose want to install the software.
After that it works fine by itself.

**Comment by probonopd** [comment]
Strange. What did you enter in the password field? Nothing?
Did you set up a password when you installed helloSystem to disk?

**Comment by louies0623** [comment]
The password is only three digits for testing, I did set a password during installation.

**Comment by probonopd** [comment]
So, you are running helloSystem from disk. When you installed it to disk, you had set a password. When you tried to install an application, you were asked for the password, and you entered the correct password. But you got the lecture window?

**Comment by louies0623** [comment]
It will appear lecture window first and then press OK, then there is no password asking window.

**Comment by Hierosme** [comment]
Is it possible the lecture is play in same, but the sk9ng password is done on a background ?

 That should be the responssability to the askpass app to display the lecture message in same time it prompt for password...

**Comment by probonopd** [comment]
I don't know yet what is causing this. Fixes welcome.

**Comment by Hierosme** [comment]
Then it require a diagnostic.

It look to have a lib use in helloSystem it forward error message play in the background to a DialogMessageBox.
i suspect askpass and the DialogMessageBox to not work as expect in that case.

It have a esay way to reproduse teh error ?
If not it will be more difficult to get a contributor fixe.

**Comment by probonopd** [comment]
> It have a esay way to reproduse teh error ?

Yes, we need to find a way to reproduce it. Currently I can't reproduce it.

**Comment by Hierosme** [comment]
@louies0623 how you do for get that trouble ?

@probonopd may be by custum the sudoers.conf and put **lecture** to **alway**.

**Comment by Hierosme** [comment]
could you point me on the askpass code and the code it convert background message to QMessageBox ?

**Comment by probonopd** [comment]
Either `/usr/local/bin/askpass` or `/usr/local/bin/launch` is doing that. (`launch` turns stderr output into QMessageBox with yellow a exclamation mark if a process run by it exits with exit code != 0)

**Comment by Hierosme** [comment]
/usr/local/bin/askpass and /usr/local/bin/launch are helloSystem native tools ? it havent a git repository where contribute ?

i'm pretty sure about that just because the sudo lecture case is not cover by the code .
anyone have make a test with sudoers.conf modify for got lecture=alway ?

One temporary workarround is to disable the sudo lecture ... we dont care about sudo lecture in that case ...

**Comment by probonopd** [comment]
https://github.com/helloSystem/ISO/blob/experimental/overlays/uzip/hello/files/usr/local/bin/askpass

https://github.com/helloSystem/launch

**Comment by Hierosme** [comment]
Because that the first time sudo is start. 

And Sudo is inside the application by design ....
