### ISSUE TITLE
Add vlc player

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#177]
![image](https://github.com/helloSystem/Utilities/assets/44593430/cc26f4d8-54cd-415c-9b53-26f687d75c79)
Need an easy-to-use media player.
The mpv player is not what we need, because the GUI is not "friendly" to the user.

**Comment by probonopd** [comment]
If I remember correctly, VLC ships its own whole set of codecs different from the ones the rest of Qt uses. We don't want this for space reasons on the Live ISO.

**Comment by louies0623** [comment]
So can it be used for "sideloading" downloads on the Internet?

**Comment by louies0623** [comment]
Then add it to the network "sideload" and let users download it separately, so there is no need to add it to the ISO.
