### ISSUE TITLE
Add Chromium or Brave browser on menu.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#178]
Although there is a librium browser available, it does not mean that it can be accepted by users.

**Comment by Hierosme** [comment]
As user Brave is require to me.

**Comment by Hierosme** [comment]
And the App SandBox provide by Chromium is use for Application like Team ...

**Comment by probonopd** [comment]
[Iridium Browser](https://iridiumbrowser.de/) is an ungoogled version of Chrome.

**Comment by louies0623** [comment]
How about [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium)

**Comment by probonopd** [comment]
Please only suggest software that is available in pkg and that you have verified to work properly on helloSystem.

What is wrong with the browsers we already have in the menu? Did you try Iridium?

**Comment by louies0623** [comment]
I originally wanted to ask about vivaldi, but after checking, they didn't provide it; users only want to install and use software that is "customary and familiar to general customers", so that Appimage can be executed in Hello system without additional strange settings, which is  is what we expected.

**Comment by louies0623** [comment]
Tried Iridium, the default homepage qwant does not support my country...

**Comment by probonopd** [comment]
I always use about://blank as the homepage in ever browser.

**Comment by probonopd** [comment]
I have not changed its default settings.

**Comment by louies0623** [comment]
I understand, will you adjust its default search engine later?

**Comment by Hierosme** [comment]
Brave got they plugins as native (dont know about sponsorblock).
https://brave.com/shields/

Iridium Browser is really the top of the top, but it lake a bit with cross platform, then brave look to be one of rare browser for every familly devices.

in 2023 with cloud a powerfull browser is really important.
clearly chromium (as main projet parent) have totally win the war.

Iridium is totally my dream browser, but i use brave due to cross platform capability, i'm not fan with the crypto thing, or virtual money, but my children have ask me to let him disable they options by him self. 
Then the default setting of Brave is officially OK and require for children's freedom :)

**Comment by louies0623** [comment]
> Possibly. I think even more important would be to preinstall:
> 
> * uBlock Origin
> * I don't Care About Cookies
> * Sponsorblock
> 
> extensions...

Just let users install extensions themselves, otherwise users will be too offended.

**Comment by Hierosme** [comment]
i like a lot you analyse, when a search engine block certain countries (or certain topic):

The engine **Is useless**

**Comment by twatel** [comment]
+1 Brave

**Comment by louies0623** [comment]
Maybe can add the option to select the search engine that the user wants during the first startup of librium, as shown in the figure, which will be helpful, and you don’t need to add Brave.
![attach_0yuqxo61ijhioo8a441qsoab4ebyrocb](https://github.com/helloSystem/Utilities/assets/44593430/4405b2be-d1a2-4799-87b7-5cf81f0f0194)

**Comment by louies0623** [comment]
@probonopd Another point is Brave browser, which at least provides web page translation function, which I really need (when I send you a message). Although Firefox also has it, Firefox is not as fast as Brave.

**Comment by probonopd** [comment]
Check out, e.g.,
https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj

**Comment by louies0623** [comment]
I still use the Google Translate plug-in because it doesn’t have traditional Chinese and I can’t use it.
