### ISSUE TITLE
Add Xviewer

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#180]
This is important for image processing or photography users.
![image](https://github.com/helloSystem/Utilities/assets/44593430/988ce9cb-e112-48c8-b95e-c06db1456eb7)

**Comment by probonopd** [comment]
Can be installed from https://www.freshports.org/graphics/xnview/ but apparently only 32-bit.
It will not be part of the helloSystem default installation.

**Comment by louies0623** [comment]
Wait, 32-bit software won't run on a 64-bit system?

**Comment by probonopd** [comment]
Only if 32-bit compatibility libraries are also installed.

**Comment by louies0623** [comment]
Otherwise, when downloading, if additional packages are needed, they should be processed directly in the download program, and there is no need to put them in the CD.
