### ISSUE TITLE
Add telegram or signal on menu

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#181]
![image](https://github.com/helloSystem/Utilities/assets/44593430/698cf3a7-1ee3-4229-ab90-eff4d339c1d3)
https://vermaden.wordpress.com/2021/09/06/freebsd-desktop-part-27-configuration-netflix-signal-telegram/

**Comment by probonopd** [comment]
Telegram is evil as long as it requires a phone number.
helloSystem will not feature services that require phone numbers because it is _very_ bad for privacy.
