### ISSUE TITLE
Add like MidnightBSD Application Store

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#182]
https://github.com/MidnightBSD/mport-manager
(Specially to replace the terminal installation that is easy to get lost), maybe we can use this without creating another manager.

**Comment by probonopd** [comment]
At this point it is not decided yet whether we want non-technical (non-terminal) users to interact with pkg.

Qt is the native toolkit for helloDesktop.
In case we want that, we will go for a Qt based tool like OctoPkg or write a simpler one.
But we won't include a Gtk based tool.

**Comment by louies0623** [comment]
Otherwise, I'm actually thinking, maybe use a web application store, and then the applications inside are processed with Qt simple Browser, like as ubports open store web app.
