### ISSUE TITLE
Add Palemoon browser 

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#183]
Although there is Firefox available, but its interface and CPU power consumption are too bloated, and an easy-to-use and light browser is needed.

**Comment by probonopd** [comment]
Looks like the build is broken:

https://www.freshports.org/www/palemoon/

**Comment by grahamperrin** [comment]
[Using package build records at pkg-status.freebsd.org](https://people.freebsd.org/~grahamperrin/pkg-status/)

**Comment by probonopd** [comment]
Thanks @grahamperrin but it doesn't seem to find anything for palemoon:

![image](https://github.com/helloSystem/Utilities/assets/2480569/0a26aa04-c9cb-49d3-b13c-c443f78dbe28)

**Comment by grahamperrin** [comment]
From the guide: 

> 2. in the Search field, enter the name of a jail

_palemoon_ is not the name of a jail.

If, for example, you want a jail that relates to FreeBSD 13⋯, then your first two keystrokes can be:

<kbd>1</kbd><kbd>3</kbd>

**Comment by probonopd** [comment]
Got it. Even when following the instructions to the letter, I can't seem to find information on palemoon (presumably because there is no way to search across _all_ builds on _all_ builders)?

**Comment by grahamperrin** [comment]
A port-specific search across all would not yield meaningful results. 

What's the name of the jail?

**Comment by probonopd** [comment]
I am looking for the reason why palemoon packages have not been built for almost all architectures and versions:
https://www.freshports.org/www/palemoon

So, almost all jails (except FreeBSD:11:aarch64 and FreeBSD:12:aarch64).

**Comment by grahamperrin** [comment]
~~Please name a single jail. The one that's of most interest.~~

~~Working through a focused example should help you, and other readers, to work through things in the future.~~

----

> <https://www.freshports.org/www/palemoon>

@louies0623 please observe the second line of the details: 

![image](https://github.com/helloSystem/Utilities/assets/192271/1b429b82-70ab-4fc5-ac3f-781292ccd924)

Pictured on the tombstone, the letters **RIP** – [rest in peace](https://en.wikipedia.org/wiki/Rest_in_peace) (_requiescat in pace_). See: 

- <https://www.freshports.org/faq.php#deleted>.

**Comment by probonopd** [comment]
![image](https://github.com/helloSystem/Utilities/assets/2480569/3dab0003-6f72-4856-9e61-1eb9c710f3cf)

Oh wow. If the port has been deleted, this bears two questions:
* Why is there still a page on FreshPorts for it?
* What was the reason for deletion?

**Comment by grahamperrin** [comment]
With FreeBSD's search service, you can't tell whether a port existed before deletion: 

- <https://ports.freebsd.org/cgi/ports.cgi?query=Palemoon&stype=name&sektion=www>

> * Why is there still a page on FreshPorts for it?

**Information** – including whether a port is deleted.

Occasionally, a port is revived. [security/pam_fprint](https://www.freshports.org/security/pam_fprint/), for example: 

1. at the beginning of the second line, click the version number to reveal history in reverse chronological order
2. uppermost, at the time of writing, is the revival
3. the preceding commit (below) was the removal.

**Comment by grahamperrin** [comment]
> What was the reason for deletion?

At <https://www.freshports.org/www/palemoon>, click the version number to reveal the history.

This case is extraordinary. 

Relevant information is within the bug report (251117) that is linked from within the first of the two commit messages that were logged on 15 Feb 2021. For convenience: 

- <https://bz-attachments.freebsd.org/attachment.cgi?id=243622> is an A3 landscape PDF of the report, as it appeared before I created (and attached) the PDF.

**Comment by probonopd** [comment]
@louies0623 looking at that, it seems unlikely that Palemoon will be available for FreeBSD soon. Hence closing.

Thanks @grahamperrin for helping me find the history.

**Comment by louies0623** [comment]
Thank you for your hard work. I may be too naive, but this is my idea. Using Appimage as the main source of downloading applications (sideloading) from the Internet means that all the software installed on the menu are appimage executable files, which will save a lot of adding Time to newly install software.

**Comment by probonopd** [comment]
Maybe there will be a Palemoon AppImage one day that can run on FreeBSD. It sure would be nice to have.

**Comment by louies0623** [comment]
Maybe we need a converter something like Wine to execute Linux appimage on BSD.

**Comment by probonopd** [comment]
Yes, that is how we are running AppImages on FreeBSD: Using the Linuxulator.

**Comment by grahamperrin** [comment]
<https://github.com/helloSystem/Utilities/issues/183#issue-1815786407> @louies0623 were you aware of Pale Moon for FreeBSD?

[Pale Moon downloads](https://www.palemoon.org/download.shtml)

- two betas.

**Comment by probonopd** [comment]
Works nicely for me:

![image](https://github.com/helloSystem/Utilities/assets/2480569/ce99af1f-55ce-4117-a275-612d9635d374)

Personally, I always like it when one can download binaries directly from the author without having to wait until (old versions of) applications land in package repositories.

**Comment by louies0623** [comment]
> [#183 (comment)](https://github.com/helloSystem/Utilities/issues/183#issue-1815786407) @louies0623 were you aware of Pale Moon for FreeBSD?
> 
> [Pale Moon downloads](https://www.palemoon.org/download.shtml)
> 
> * two betas.

I know, just the appimage source will have a new version sooner than waiting until there is a BSD version.

**Comment by probonopd** [comment]
> Unfortunately it seems like it doesn't support the global menu.
Maybe a feature request could be opened for it.

Actually it is there, but it is not enabled by default - for whatever reason.

So, to enable it, go to about:config, search for `ui.use_global_menubar` and set it to `true`.

Works instantly:

![image](https://github.com/helloSystem/Utilities/assets/2480569/c14ec74e-99a5-4bd4-ad89-f512d824e267)

**Comment by probonopd** [comment]
Now, this is a serious bummer. I need

* uBlock Origin
* I don't care about cookies
* SponsorBlock

![image](https://github.com/helloSystem/Utilities/assets/2480569/ee2eaa5e-749a-4f85-b79a-9651b606496f)

**Comment by probonopd** [comment]
> I know, just the appimage source will have a new version sooner than waiting until there is a BSD version.

The FreeBSD version from the Pale Moon website is the very latest version:

![image](https://github.com/helloSystem/Utilities/assets/2480569/50d67566-209d-4bad-ba4c-68c8cef75fe3)

**Comment by louies0623** [comment]
Use [uBlock Origin](https://github.com/gorhill/uBlock)

**Comment by probonopd** [comment]
Found this
https://addons.palemoon.org/extensions/

But there is no https://github.com/ajayyy/SponsorBlock/ for it ;-(

**Comment by louies0623** [comment]
sorry please use uBlock Origin Legacy

**Comment by louies0623** [comment]
Then curious to ask, is Linuxulator attached to the Hello system?

**Comment by probonopd** [comment]
Linuxulator comes with FreeBSD and is in helloSystem. But it is not needed to run Pale Moon, since they provide a FreeBSD version.
