### ISSUE TITLE
Install.app : Need an update method without wiping user data

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#185]
We need a way to update the system directly from the CD, because it is a waste of time to re-download the software pkg or copy the test files to test whether the Hello System Development Preview version is running normally.

Like the old mac os update (this is also like the Windows CD's Setup.exe update method) for example: easy install.

Simply speaking, it is to upgrade or install the system by installing software, and it does not need to be connected to the Internet.

**Comment by probonopd** [comment]
https://github.com/helloSystem/ISO/issues/55
