### ISSUE TITLE
Make it possible to add two layouts in Keyboard.app

### ISSUE THREAD

**Issue by UnixAwesome** [helloSystem/Utilities#192]
Make it possible to add two layouts in Keyboard.app, and add the ability to assign a keyboard shortcut to switch between them.

**Comment by probonopd** [comment]
Unlikely that this gets implemented. In helloSystem the keyboard layout (keyboard language) should be set automatically to the correct layout (what is actually printed on the keys). 

We have this working for the [Raspberry Pi Keyboard and Hub](https://www.raspberrypi.com/products/raspberry-pi-keyboard-and-hub/) so far This is where our energy goes. Manually changing the keyboard layout should hopefully be no more needed in the future.
