### ISSUE TITLE
Hardware probe: Pressing show Hardware probe on the first page does not display the hardware list.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#196]
Hardware probe: Pressing show Hardware probe on the first page does not display the hardware list.
![image](https://github.com/helloSystem/Utilities/assets/44593430/d22b7ff5-2766-456a-891a-2b7e91edee43)

**Comment by probonopd** [comment]
What kind of system are you running there? That screenshot looks like an ancient version (many years old)?

**Comment by louies0623** [comment]
That's an example picture.

**Comment by probonopd** [comment]
Does this also happen on the Live ISO when you set/leave the language to English?
Possibly some language setting is preventing Hardware Probe from running correctly?
Thanks for testing and thanks for your feedback.

**Comment by louies0623** [comment]
Yes, Live ISO is set to English, same thing.

**Comment by probonopd** [comment]
if it works in verbose mode, then the new Filer works correctly and the old Filer is broken...

**Comment by louies0623** [comment]
Maybe it can be turned off because there is a visual list, otherwise if you still want to use it, reopen this issue.
