### ISSUE TITLE
Wifi not connected icon is too shallow

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#198]
![20230906_155156](https://github.com/helloSystem/Utilities/assets/44593430/7cd1acf5-10d3-40f2-ae96-945335789c4a)
It's easy to think that Wifi isn't working.

**Comment by probonopd** [comment]
Can you find us a better icon please? Thank you.

**Comment by louies0623** [comment]
Can you provide a picture of this?

**Comment by louies0623** [comment]
https://launchpad.net/ubuntu/xenial/+source/ubuntu-themes

[ubuntu-mono-light.zip](https://github.com/helloSystem/Utilities/files/12546889/ubuntu-mono-light.zip)

I think I'll just use this one. Although it's an old Ubuntu stock, it has the system icon we need in the upper right corner. However, the consistency of the sound icon also needs to be fixed.

**Comment by probonopd** [comment]
Please let me know the filenames. Thanks!

**Comment by louies0623** [comment]
nm-no-connectoion.svg

**Comment by probonopd** [comment]
Continues in https://github.com/helloSystem/Utilities/issues/204
