### ISSUE TITLE
Hardware probe: List of hardware that needs to be visualized

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#201]
Can be used in the Show Hardware Probe and displayed clearly instead of looking for it in the folder.
![image](https://github.com/helloSystem/Utilities/assets/44593430/dc5718ea-298c-46f7-8dc1-7607a81ab226)

![images - 2023-09-08T063714 618](https://github.com/helloSystem/Utilities/assets/44593430/d2bf1dd5-d5c4-4561-a935-0ebaa936388d)

**Comment by probonopd** [comment]
Please retest in build 0I41 or later. Thanks!

**Comment by louies0623** [comment]
It's basically ok, but I hope it can be layered like the example picture.

![20230909_090725](https://github.com/helloSystem/Utilities/assets/44593430/ce691ecb-0938-4371-b5e6-cb7270cd8a4c)

![macos-catalina-mbp-system-report-hardware](https://github.com/helloSystem/Utilities/assets/44593430/82c37e53-4359-4eff-9e90-f61e3d121577)

**Comment by probonopd** [comment]
For that we would need to use a QTreeView instead of a QLIstView.

I won't invest more time into this for now but pull requests which implement this are welcome.
