### ISSUE TITLE
Consistently use the ubuntu-mono light status icon

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#204]
This is extracted from the old version of ubuntu-mono light as an icon displayed by the default top device.

[ubuntu-mono-light status.zip](https://github.com/helloSystem/Utilities/files/12564468/ubuntu-mono-light.status.zip)

- [ ] network 
- [ ] wifi
- [ ] Aoudio 
- [ ] Battery 
- [ ] Bluetooth

**Comment by probonopd** [comment]
@louies0623 it would be great if you could send a pull request.

The icons need to go to https://github.com/helloSystem/Utilities/tree/master/System/Network.app/Resources in png format, and the code needs to be changed similar to

https://github.com/helloSystem/Utilities/blob/20a9b7d9dce02d107e45c6395976194239f1d2f6/System/Network.app/Network#L337

Thank you very much!

**Comment by louies0623** [comment]
PNG file
[ubuntu-mono-light Png.zip](https://github.com/helloSystem/Utilities/files/12577254/ubuntu-mono-light.Png.zip)

**Comment by probonopd** [comment]
Can you please give me just the one icon from the screenshot, in the correct size that is needed. Thanks!

**Comment by louies0623** [comment]
![netstatus-disconn](https://github.com/helloSystem/Utilities/assets/44593430/29c3f15a-72f0-46e9-a58e-3d1ac6b9ff96)

**Comment by probonopd** [comment]
Since we don't have  color there, we'd need the last icon with a X through it, or something like that.

**Comment by louies0623** [comment]
I actually think this is good, and it looks good in Unity, but if you add an X icon, I don’t recommend modifying it, because it will become inconsistent and the meaning will also become the device failure.

**Comment by louies0623** [comment]
@probonopd I would have liked the color because it would quickly draw attention to the problem there.
I can make something like.
![20231004_070019](https://github.com/helloSystem/Utilities/assets/44593430/0546eab0-ae23-4db1-9ce0-51eb81794ff8)

**Comment by louies0623** [comment]
@probonopd This?
PNG
![disconn](https://github.com/helloSystem/Utilities/assets/44593430/d6e8433a-1fe1-4a40-a170-ba22eabc170c)

SVG File
[disconn-svg](https://github.com/helloSystem/Utilities/assets/44593430/4872cf4c-8f8a-49ef-bac3-781c56cdc03e)

**Comment by louies0623** [comment]
@probonopd 
PNG
![disconn](https://github.com/helloSystem/Utilities/assets/44593430/3b241c06-9a7f-4aa9-bcfc-e1ff39ef6a37)

SVG File
![disconn.svg](https://github.com/helloSystem/Utilities/assets/44593430/275b5aa2-9cc4-435d-ad4c-183e61bf37e9)

Update: 23.10.6. Fixed visual bugs

**Comment by probonopd** [comment]
Please send one pull request for each change you would like. Thanks!
