### ISSUE TITLE
Proccesses.app Icons update

### ISSUE THREAD

**Issue by Hierosme** [helloSystem/Utilities#208]
## PNG
![utilities-system-monitor](https://user-images.githubusercontent.com/44593430/267874232-bd458d75-0617-44a2-8ba1-4f38f0e48c40.png)
![process-stop](https://user-images.githubusercontent.com/44593430/267874248-7ca89374-3d38-4651-9949-521eda8d3387.png) ![info](https://user-images.githubusercontent.com/44593430/267874242-76bb3aff-55f1-4ad9-afd5-b26367c5050d.png) ![clock](https://user-images.githubusercontent.com/44593430/267874234-e8301554-fb23-41ba-884b-49810c966d1e.png)

Here icon set

**Comment by Hierosme** [comment]
@louies0623 how i love the icon set cher.

I do it ASAP.

**Comment by louies0623** [comment]
@Hierosme None of that was done by me, it was all extracted from here
https://launchpad.net/ubuntu/+source/humanity-icon-theme
