### ISSUE TITLE
Icon missed 

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#213]
![20230924_184348](https://github.com/helloSystem/Menu/assets/44593430/48b54e39-c8f8-444a-9873-f4ef02455bca)
![20230924_131624](https://github.com/helloSystem/Menu/assets/44593430/f8d8ec1b-806f-4d48-8d8e-427b8e34b087)

**Comment by probonopd** [comment]
https://github.com/helloSystem/Utilities/blob/master/Utilities/Processes.app/Resources/Processes.svg must be a png.

**Comment by probonopd** [comment]
Maybe https://github.com/helloSystem/Utilities/pull/209 fixes this.

**Comment by probonopd** [comment]
Please comment here if it does not fix it.
