### ISSUE TITLE
Display. app HiDPI set

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#229]
As laptops begin to have higher resolutions, the text screen of window programs will become extremely small, and a high-resolution screen processing example is required, as shown in the figure.
![image](https://github.com/helloSystem/Utilities/assets/44593430/8e1fb5c0-05d6-4a6f-9a3d-5a820534b2cf)
![image](https://github.com/helloSystem/Utilities/assets/44593430/d7e609c9-aab3-4b18-aeb0-a7a876332e93)

**Comment by probonopd** [comment]
We are detecting HiDPI automatically as part of `start-hello`, so the user does not have to configure anything.
