### ISSUE TITLE
Improve Logs utility

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#23]
* Allow to search through all logs
* Highlight lines that contain the word "error", "fail", "critical", "warn".. in red

**Comment by kallaip** [comment]
I think this is a good issue for me to get familiar with PyQt, please assign it to me.

**Comment by probonopd** [comment]
hello @kallaip

This is a great first issue. But please keep in mind that we use PyQt for the "light" applications only. The "heavy lifting" applications like Filer, Menu, and Dock are not written in Python.

So this ticket may be too easy for you...

**Comment by kallaip** [comment]
Thanks, I'm also planning to touch some "heavier" issues, I'm just getting familiar with the environment by now :)

**Comment by kallaip** [comment]
Hi  @probonopd,
I would like to create a branch from utilities/master, but it seems I don't have permissions. My intent is to improve the log viewer, as indicated above, plus to add som other features, f.g. multi-tabbed window, etc.

**Comment by probonopd** [comment]
Hi @kallaip, please create a fork:

![image](https://user-images.githubusercontent.com/2480569/104124556-cfe0ba80-5351-11eb-882c-2bbf0a01af63.png)

Make your changes in your fork, then send a Pull Request.

Ideally make small changes at a time, not one giant Pull Request with lots of changes at once. This will allow for faster review and better discussion.

Welcome to helloSystem!

**Comment by probonopd** [comment]
Hi @kallaip please see the changes I have made so far.

> Highlight lines that contain the word "error", "fail", "critical", "warn".. in red

is implemented.

**Comment by grahamperrin** [comment]
Also: 

* https://github.com/helloSystem/ISO/issues/194 for missing logs
* find within all logs
* find within an individual log
* filter all logs
* filter within an individual log
* add any necessary menus (you'll need at least one, **Edit**, for the **Copy** and **Select All** commands) and make them keyboard accessible
