### ISSUE TITLE
Keyboard.app checkboxes not working in helloSystem

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#3]
![image](https://user-images.githubusercontent.com/2480569/101258878-baaab780-3725-11eb-8202-cbbcb3371928.png)

Apparently those do not work in a Qt based environment. They did work in GNUstep. Possibly Qt handles these things differently in the xcb plugin and we'd need to hook in there?

**Comment by grahamperrin** [comment]
Probably fixed; https://github.com/helloSystem/Utilities/commit/757aa02bbdf7fb649432b08d5db9c033bd502589
