### ISSUE TITLE
If an application has no more than one non-tabbed window, Meta-W should close the window

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Utilities#31]
Windows for applications such as Boot Environments, Desktop, Keyboard, Mouse, Print Settings, Screen Settings, Sharing, Shortcut Keys and Sound do not close when expected. 

(Windows of Wireless Networks could not be tested in a VirtualBox guest.)

Under `/Applications/Utilities` I found Calculator similarly non responsive to the keyboard shortcut, so I guess that it's a generic issue.

**Comment by grahamperrin** [comment]
Is this partially a duplicate of <https://github.com/helloSystem/Menu/issues/39>? 

(Sorry … I did perform a search before raising this issue, not sure whether/how I missed the earlier issue.)

**Comment by probonopd** [comment]
Yes. Implementing helloSystem/Menu#39 will fix this. So let's continue the discussion in that ticket.
