### ISSUE TITLE
Screenshot preferences should be persistent

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Utilities#39]
If I prefer a delay of five seconds, the preference should be remembered. 

And so on …

**Comment by probonopd** [comment]
We need to find another screenshot application then (or write one...)

**Comment by grahamperrin** [comment]
[deskutils/lumina-screenshot](https://www.freshports.org/deskutils/lumina-screenshot/) maybe?

Does https://www.freshports.org/deskutils/lumina-screenshot/#dependencies satisfy the preference for Qt?

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/Utilities/issues/39#issuecomment-767025475

> …  need to find another screenshot application …

### graphics/ksnip

https://github.com/helloSystem/ISO/blob/36941e228bde804372769ca6333c8ff76d0735e3/settings/packages.hello#L67

Fixed a few weeks ago: 

* https://bugs.freebsd.org/bugzilla/show_activity.cgi?id=252229

– expect it to work with FreeBSD `12.2` but not (EOL) `12.1`.

**Comment by grahamperrin** [comment]
### ScreenGrab

https://github.com/lxqt/lximage-qt/issues/392#issuecomment-773317231 @tsujan suggests using ScreenGrab https://github.com/lxqt/screengrab

I can't find it on FreshPorts, and (unless I'm missing something) it's not present after installing [x11-wm/lxqt](https://www.freshports.org/x11-wm/lxqt/) so I assume that it's simply not ported to FreeBSD.

**Comment by jsm222** [comment]
You're right screengrab is not ported.

**Comment by jsm222** [comment]
It compiles and works on FreeBSD without modifications, I will make a port..

**Comment by probonopd** [comment]
Thank you very much @jsm222 - please give us a ping once a package has landed.

**Comment by jsm222** [comment]
https://www.freshports.org/x11/screengrab/
You can keep an eye on the pkg repo yourself :-)

**Comment by grahamperrin** [comment]
https://pkg-status.freebsd.org/builds?type=package ▶ _122amd64_ ▶ await the next runs for _quarterly_ and _default_

**Comment by probonopd** [comment]
Excellent. That was quick @jsm222, thank you very much :+1:

**Comment by grahamperrin** [comment]
https://hellosystem.github.io/docs/developer/ux-guidelines.html#avoiding-configuration-options

> KDE Plasma is recommended as an alternative for users who wish to configure and customize every aspect of the system.
