### ISSUE TITLE
Desktop: Not in Hello System Style

### ISSUE THREAD

**Issue by rbircher** [helloSystem/Utilities#48]
Hi all

The Desktop app is not in Hello System Style

![not_consistent_design](https://user-images.githubusercontent.com/4296975/107974258-9c2f2b00-6fb6-11eb-89a0-b8333d73b51b.png)

Maybe I can tackle this Bug by my self

**Comment by probonopd** [comment]
Thanks for reporting.
This is an effect of the workaround for https://github.com/helloSystem/QtPlugin/issues/2, so let's continue the discussion there.
