### ISSUE TITLE
Keyboard Layout not saved

### ISSUE THREAD

**Issue by rbircher** [helloSystem/Utilities#58]
Steps to reproduce

- Install a New HelloSystem from the ISO
- Make sure you are on the Installed version and not on the live System

Your Keyboard Layout should be EN-us

- Change the Keyboard Layout to German
- Verify that your the keyboard layout is in German
- Shutdown HelloSystem
- Restart HelloSystem
- Check the keyboard layout

Expected: Keyboard layout in German

Instead: Keyboard layout in EN_us

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/hello/issues/93

https://github.com/helloSystem/ISO/issues/110

**Comment by probonopd** [comment]
Did you use "Save" from the menu in the **Keyboard** preferences application?

**Comment by rbircher** [comment]
Ok, maybe i have not saved it, yes... will try this with the next build. But for sure it dosen't work with the cmd tools from FreeBSD.

**Comment by probonopd** [comment]
> But for sure it dosen't work with the cmd tools from FreeBSD.

Please describe exactly the steps you took there.

**Comment by rbircher** [comment]
Open Command Line and type

` setxkbmap ch`

**Comment by probonopd** [comment]
> setxkbmap ch

Does this command perist the changed layout somewhere? Where?
I think it doesn't.

**Comment by linuxkettle** [comment]
I think we need a Localisation Preference app to change keyboard layout, language and timezone and save the changes to a script sourced by localize.

**Comment by probonopd** [comment]
Yes, but we should also have it save stuff to the EFI variables that Apple does, if they are not set already. So that things "just work" if you run another Live iSO.

**Comment by probonopd** [comment]
We are now also writing a `/usr/local/var/localize/include` file: 
 https://github.com/helloSystem/Utilities/commit/14351d5683652abb36046139efb16c04a4a49441
