### ISSUE TITLE
Logs.app should include /var/log/messages and other useful logs

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Utilities#59]
From <https://github.com/helloSystem/ISO/issues/193#issue-844200324>: 

17. opened Logs.app
18. couldn't easily see `/var/log/messages`

My instinct is that (partly to avoid reinventing the wheel) helloSystem should build upon an existing application from another project. If [the list of unwelcome technologies](https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies) precludes this possibility, then: 

* Logs.app should be more comprehensive. 

Thank you

**Comment by probonopd** [comment]
That was an easy fix:

https://github.com/helloSystem/Utilities/blob/c6819ef33269835ba6abc728872197f2a94776d4/Utilities/Logs.app/Resources/logs.py#L134

Please let me know if you think other files should be added.
