### ISSUE TITLE
Volume: Make slider appear in the correct place

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#65]
Volume: Make slider appear in the correct place. Right now it appears too far on the right if you have additional upper-right-hand-side icons in the menu.

https://github.com/helloSystem/Utilities/blob/714c12cb69209f24e7ddc6571ee322b9d29b2d0b/System/Volume.app/Volume#L169-L173

may need to use `QCursor.pos()`

like in 
https://github.com/anaynayak/buildnotify/pull/194/files

**Comment by linuxkettle** [comment]
Same issue as Network.app
