### ISSUE TITLE
Add IBUS input method as the default input method

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#72]
For [Japanese, Korean, Indian, Thai, Vietnamese, Chinese (Traditional), Chinese (Simplified)] users, add input methods, as far as I know it supports the most extensive and complete languages.

https://en.wikipedia.org/wiki/Intelligent_Input_Bus
https://github.com/ibus/ibus

**Comment by probonopd** [comment]
Is there a non-Gtk, non-Linux, non-Red Hat way of achieving a similar thing?

**Comment by louies0623** [comment]
I never thought that ibus has a problem in German, no wonder Ubuntu will add keyboard input method system option in language support in system settings.

![DRVK5](https://user-images.githubusercontent.com/44593430/123547078-ed83ce00-d791-11eb-81ae-1e418832404c.png)

**Comment by louies0623** [comment]
But I also tend to use the most extensive iBus as the default because it supports the most extensive, and users can also select the input method type by "Language support-keyboard input method"

**Comment by louies0623** [comment]
There is one more thing. You should add a new language switch in the upper right corner of the menu. Just like Mac or unity, choose the language you should choose. This should reduce the number of incorrect input because the video I saw is solved like this (maybe).
![UUnity_1_open_text_entry_settings-en](https://user-images.githubusercontent.com/44593430/123549502-efeb2580-d79b-11eb-9bb8-ae50ce002b7c.png)
![unnamed (1)](https://user-images.githubusercontent.com/44593430/123549514-00030500-d79c-11eb-9557-45d724e115ea.png)

**Comment by probonopd** [comment]
This is an anti-feature if you ask me.

helloSystem is about making things simple, not complicated.
The language should match what is physically printed on the keyboard, and it should be auto-detected.

You have a British keyboard? Then it should be recognized as such. Or have a US keyboard? Then it should be recognized as such. (This is how it works with Raspberry Pi keyboards currently.)

**Comment by louies0623** [comment]
It’s just that if it’s a keyboard and a word, it’s impossible in my language.

This is the language i use
Because in my language, there are 7 ways to input a word.
![unnamed](https://user-images.githubusercontent.com/44593430/123548651-3dfe2a00-d798-11eb-8cde-f83e23c1e735.png)
Then there are 5 ways to write in one word
![91683835-0d119080-eb99-11ea-8e42-c7cfabb9cfc8](https://user-images.githubusercontent.com/44593430/123548782-d09ec900-d798-11eb-9976-56ea4005e1fd.png)
![1200px-漢字文化圈／汉字文化圈_·_한자_문화권_·_Vòng_văn_hóa_chữ_Hán_·_漢字文化圏 svg](https://user-images.githubusercontent.com/44593430/123548844-0b086600-d799-11eb-9201-ae541b23a6fa.png

**Comment by louies0623** [comment]
Note:
It is indeed very important to automatically detect the keyboard configuration, if the configuration is not complete, you still have to select the layout in the keyboard settings.

**Comment by probonopd** [comment]
Let's talk about this topic in https://github.com/helloSystem/docs/issues/34.
