### ISSUE TITLE
Network: Do not ask for a password if the WLAN does not require one

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#73]
In WiFi without a password, you need to enter the password. After you press the OK button without entering any text, the password error is displayed.

**Comment by linuxkettle** [comment]
Just enter anything.

**Comment by linuxkettle** [comment]
Random 8 letters.

**Comment by probonopd** [comment]
We should check whether the network requires a password, and only ask for one if it does.

**Comment by probonopd** [comment]
In 360f937 I have added an attribute "flags" for each network.

Something like 

```
if "PSK" in getattr(self.wirelessGroup.checkedAction(), "flags"):
```

should be used, and only if the string "PSK" is part of the "flags" string we should show the password dialog.

However, I was not yet successful in getting it to connect to a network that uses no password (e.g., public hotspot).

@linuxkettle do you have an idea?

**Comment by probonopd** [comment]
I think I have implemented skipping the password dialog for networks that do not require one, but I cannot connect to an unencrypted network. It will always connect to the encrypted one I had connected to previously. @linuxkettle do you have any idea?

**Comment by jsm222** [comment]
Hints set_network 1 key_mgmt NONE
And the prority flag

**Comment by probonopd** [comment]
> set_network 1 key_mgmt NONE

That was the key. Thank you so much!
