### ISSUE TITLE
Screen layout editor : If there is only one monitor, lock the Active Primaryvm option

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#83]
On only one screen, these two options must be locked to avoid unnecessary trouble . 0F28
![image](https://user-images.githubusercontent.com/44593430/125348697-900f8580-e32a-11eb-9056-9e6e07da3acc.png)

**Comment by linuxkettle** [comment]
There's no need to even open that app on a system with one screen.

**Comment by louies0623** [comment]
> There's no need to even open that app on a system with one screen.

No, this function should remain on one screen.
So as not to need to set.

**Comment by probonopd** [comment]
This app will get replaced by something written in Qt anyway, so we will not invest any time in improving it.
