### ISSUE TITLE
Network: The menu is still on the window

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#84]
"The menu is still on the window" On Wireless Network 0F28
![image](https://user-images.githubusercontent.com/44593430/125351436-15486980-e32e-11eb-9c12-ccd4d51aa039.png)

**Comment by probonopd** [comment]
This is because this application needs to run as root.
Unfortunately I have not found a way yet to have applications that are running as root to use the Global Menu.
If you know how to do this, please comment here and I will reopen.

**Comment by linuxkettle** [comment]
Before that works, we need two things fixed:

- DBus is per-user, so the menu doesn't get exported and for GTK apps,
- GTK_PLUGINS doesn't get exported, because of how sudo wipes environnement variables.

**Comment by probonopd** [comment]
We are using `sudo -E` which preserves the environment.
