### ISSUE TITLE
When the installation is complete, a notification window should be displayed

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#85]
When the installation is complete, a notification window should be displayed.
Used to inform whether the installation is completed, rather than directly execute or close.
![image](https://user-images.githubusercontent.com/44593430/125354239-2af17980-e396-11eb-95c4-052ea993d260.png)

**Comment by probonopd** [comment]
The intended behavior is that the application automatically runs after it has been downloaded. After all, the user opened it.

**Comment by louies0623** [comment]
At least there is a notification saying that the installation is complete, just like a download notification.
